### ISSUE TITLE
Pass --network host to a Docker container

### ISSUE THREAD

**Issue by nicon89** [actions/hello-world-docker-action#10]
Hi all,

I'm not sure if I'm asking this question in right place, if not, please let me know.

I'm trying to pass "--network host" to a Docker container created with:
```
runs:
  using: docker
  image: xxx
```
is there a way to do it?

**Comment by ncalteen** [comment]
Hello! Apologies for the delay in responding to this issue! Currently you cannot provide networking configuration to container actions themselves. If you're running a container action in a workflow file, you could potentially configure networking via [service containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers).

I hope this helps! If not feel free to reopen the issue with any additional information :)

**Comment by nicon89** [comment]
Thanks anyway ;)
