### ISSUE TITLE
set/entrypoint.sh: line 9: can't create /github/file_commands/set_output_xx: Permission denied

### ISSUE THREAD

**Issue by asos-danielc** [actions/hello-world-docker-action#16]
I have copied this repo example, but when the docker image is executed I get the following error:

> /entrypoint.sh: line 9: can't create /github/file_commands/set_output_e625b619-0adf-4a21-89f4-f1132b0d9516: Permission denied

I am using runner version `'2.301.1'`, and syntax:

```
#!/bin/sh -l

echo "Hello $1"
time=$(date)

echo "time=$time" >> $GITHUB_OUTPUT
echo "person=$1" >> $GITHUB_OUTPUT
```

if I change it to the old github output and it worked

```
#!/bin/sh -l

echo "Hello $1"
time=$(date)

echo "##[set-output name=time]$time"
echo "##[set-output name=person]$1"
```

Any help appreciated

**Comment by ncalteen** [comment]
Is this occurring when you run the container locally, or as part of a workflow?

**Comment by ncalteen** [comment]
Hello! I'm going to go ahead and close this for now, but if you're still running into any issues please feel free to reopen and I'll check it out soon as I can :)
