### ISSUE TITLE
not support COPY --chmod 0755

### ISSUE THREAD

**Issue by aogg** [actions/hello-world-docker-action#19]
Dockerfile:7
--------------------
   5 |     COPY --from=monokal/tinyproxy /opt/docker-tinyproxy/run.sh /docker-tinyproxy-run.sh
   6 |     
   7 | >>> COPY --chmod 0755 docker-entrypoint.sh /docker-entrypoint.sh
   8 |     # COPY docker-entrypoint.sh /docker-entrypoint.sh
   9 |     
--------------------
ERROR: failed to solve: dockerfile parse error on line 7: missing a value on flag: chmod
Error: buildx failed with: ERROR: failed to solve: dockerfile parse error on line 7: missing a value on flag: chmod

**Comment by ncalteen** [comment]
Hello! We recently made a number of updates to this repo that should resolve some of the errors like the one you're seeing. If you are still running into trouble, please feel free to comment and reopen this issue and I'll take a look soon as I can :)
