### ISSUE TITLE
Revert Action Output to Time

### ISSUE THREAD

**Issue by mattuyw** [actions/hello-world-docker-action#30]
[The commit](https://github.com/actions/hello-world-docker-action/commit/72fed7c8ea16d305e86b58fba8ebe743e6c0c218) introduced the `greeting` output which silently fails the [Github Actions Test](https://github.com/actions/hello-world-docker-action/actions/runs/8006403132/job/21868056645) and deviates from both the [documented output](https://github.com/actions/hello-world-docker-action?tab=readme-ov-file#outputs) and the companion [Github Docs documentation](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-a-dockerfile).

The following should be restored in `entrypoint.sh` to restore the `time` output.
```
echo "time=$(date)" >>"$GITHUB_OUTPUT"
```

**Comment by ncalteen** [comment]
Thanks for the input and references!

I see what you mean about the silent failure. It looks like the step to echo the output is referencing `time`, which is returning an empty string since the output does not exist. I'll revert that now!
